images:
  - 'gcr.io/$PROJECT_ID/crds-dev-doc:commit-$SHORT_SHA'

steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crds-dev-doc:commit-$SHORT_SHA'
      - '--label'
      - 'org.opencontainers.image.source=https://github.com/ripta/crds-dev-doc'
      - '--label'
      - 'org.opencontainers.image.revision=$COMMIT_SHA'
      - '--label'
      - 'net.r8y.build.trigger=$TRIGGER_NAME'
      - '-f'
      - 'Dockerfile'
      - '.'

  - id: Push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crds-dev-doc:commit-$SHORT_SHA']
