images:
  - 'gcr.io/$PROJECT_ID/crds-dev-doc:commit-$SHORT_SHA'

steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/crds-dev-doc:commit-$SHORT_SHA', '-f', 'Dockerfile', '.']

  - id: Push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crds-dev-doc:commit-$SHORT_SHA']
